Algoritmo "semnome"

Var

n: inteiro

Inicio

escreval("Digite um número de 1 a 5: ")
leia(n)

escolha n
   caso 1
      escreval("Seu número é Um")
   caso 2
      escreval("Seu número é Dois")
   caso 3
      escreval("Seu número é Três")
   caso 4
      escreval("Seu número é Quatro")
   caso 5
      escreval("Seu número é Cinco")
   outrocaso
      escreval("Esse número é inválido!")
fimescolha
Fimalgoritmo